In [3]:
import numpy as np

an_array = np.array([1,2,3])
print(an_array)

[1 2 3]


In [4]:
print(an_array.shape)

(3,)


In [7]:
array2 = np.array([[1,2,3],[4,5,6]]) # rank 2 array
print(array2)

[[1 2 3]
 [4 5 6]]


In [8]:
print(array2.shape)

(2, 3)


In [9]:
a3 = np.random.random((2,2))
print(a3)

[[0.55760421 0.60968451]
 [0.12507675 0.84738531]]


In [11]:
a3[:1]

array([[0.55760421, 0.60968451]])