In [2]:
import numpy as np

an_array = np.array([1,2,3])
print(an_array)

[1 2 3]


In [4]:
print(an_array.shape)

(3,)


In [5]:
array2 = np.array([[1,2,3],[4,5,6]]) # rank 2 array
print(array2)

[[1 2 3]
 [4 5 6]]


In [6]:
print(array2.shape)

(2, 3)


In [7]:
a3 = np.random.random((2,2))
print(a3)

[[0.90807834 0.12754793]
 [0.04858376 0.9850783 ]]


In [10]:
a3[:2,]

array([[0.90807834, 0.12754793],
       [0.04858376, 0.9850783 ]])

In [9]:
a4 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a4)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [16]:
print(a4)
print()
a4_slice = a4[:2, 1:3]
print(a4_slice)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2 3]
 [5 6]]


# Boolean Indexing

In [13]:
arr = np.array([[11,12],[13,14],[15,16]])
print(arr)
print()
print(arr.shape)

[[11 12]
 [13 14]
 [15 16]]

(3, 2)


In [14]:
filter_a = (arr > 12)
filter_a

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [15]:
print(arr[filter_a])

[13 14 15 16]


In [20]:
arr[arr %2 ==0] +=100
print(arr)

[[ 11 412]
 [ 13 414]
 [ 15 416]]


In [22]:
a1 = np.array([11,12])
print(a1.dtype)

int64


In [4]:
a2 = np.array([11.0,12], dtype=np.float64)
print(a2.dtype)

float64
