In [231]:
import numpy as np
import pandas as pd

In [232]:
df_train = pd.read_csv("train.csv")
df_test = pd.read_csv("test.csv")

In [233]:
df_train.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [234]:
df_test.head(5)

PassengerId  Pclass                                          Name     Sex  \
0          892       3                              Kelly, Mr. James    male   
1          893       3              Wilkes, Mrs. James (Ellen Needs)  female   
2          894       2                     Myles, Mr. Thomas Francis    male   
3          895       3                              Wirz, Mr. Albert    male   
4          896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female   

    Age  SibSp  Parch   Ticket     Fare Cabin Embarked  
0  34.5      0      0   330911   7.8292   NaN        Q  
1  47.0      1      0   363272   7.0000   NaN        S  
2  62.0      0      0   240276   9.6875   NaN        Q  
3  27.0      0      0   315154   8.6625   NaN        S  
4  22.0      1      1  3101298  12.2875   NaN        S

In [235]:
df_train.columns
cols = ['PassengerId', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp','Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked','Survived']
df_train = df_train[cols]
df_train.head(3)

PassengerId  Pclass                                               Name  \
0            1       3                            Braund, Mr. Owen Harris   
1            2       1  Cumings, Mrs. John Bradley (Florence Briggs Th...   
2            3       3                             Heikkinen, Miss. Laina   

      Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0      1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0      1      0          PC 17599  71.2833   C85        C   
2  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S   

   Survived  
0         0  
1         1  
2         1

In [236]:
PassengerId = df_test['PassengerId']

df_train = df_train.drop(['PassengerId','Name','Ticket'], axis=1)
df_test = df_test.drop(['PassengerId','Name','Ticket'], axis=1)
df_test.head(3)

Pclass     Sex   Age  SibSp  Parch    Fare Cabin Embarked
0       3    male  34.5      0      0  7.8292   NaN        Q
1       3  female  47.0      1      0  7.0000   NaN        S
2       2    male  62.0      0      0  9.6875   NaN        Q

In [237]:
df_train['Embarked'] = df_train['Embarked'].fillna('S')
df_test['Embarked'] = df_test['Embarked'].fillna('S')
df_train.drop("Cabin",axis=1,inplace=True)
df_test.drop("Cabin",axis=1,inplace=True)

In [238]:
df_test.head(3)

Pclass     Sex   Age  SibSp  Parch    Fare Embarked
0       3    male  34.5      0      0  7.8292        Q
1       3  female  47.0      1      0  7.0000        S
2       2    male  62.0      0      0  9.6875        Q

In [239]:
df_train['Fare'] = df_train['Fare'].fillna(df_train['Fare'].median())
df_train['Age'] = df_train['Age'].fillna(df_train['Age'].median())
df_test['Fare'] = df_test['Fare'].fillna(df_test['Fare'].median())
df_test['Age'] = df_test['Age'].fillna(df_test['Age'].median())

In [240]:
df_train.head(3)

Pclass     Sex   Age  SibSp  Parch     Fare Embarked  Survived
0       3    male  22.0      1      0   7.2500        S         0
1       1  female  38.0      1      0  71.2833        C         1
2       3  female  26.0      0      0   7.9250        S         1

In [241]:
df_test.head(3)

Pclass     Sex   Age  SibSp  Parch    Fare Embarked
0       3    male  34.5      0      0  7.8292        Q
1       3  female  47.0      1      0  7.0000        S
2       2    male  62.0      0      0  9.6875        Q

In [242]:
X = df_train.iloc[:,0:7].values
y = df_train.iloc[:,7]
X[0:2]
# y[0:2]

array([[3, 'male', 22.0, 1, 0, 7.25, 'S'],
       [1, 'female', 38.0, 1, 0, 71.2833, 'C']], dtype=object)

In [243]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 6] = labelencoder_X_1.fit_transform(X[:, 6])

labelencoder_X_2 = LabelEncoder()
X[:, 1] = labelencoder_X_2.fit_transform(X[:, 1])

onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

X[0:2]

array([[ 1.    ,  3.    , 22.    ,  1.    ,  0.    ,  7.25  ,  2.    ],
       [ 0.    ,  1.    , 38.    ,  1.    ,  0.    , 71.2833,  0.    ]])

In [244]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [247]:
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [249]:
# Importing the Keras libraries and packages
import keras
from keras.models import Sequential
from keras.layers import Dense

# Initialising the ANN
classifier = Sequential()

# Adding the input layer and the first hidden layer
classifier.add(Dense(output_dim = 4, init = 'uniform', activation = 'relu', input_dim = 7))

# Adding the second hidden layer
classifier.add(Dense(output_dim = 4, init = 'uniform', activation = 'relu'))

# Adding the third hidden layer
classifier.add(Dense(output_dim = 4, init = 'uniform', activation = 'relu'))

# Adding the output layer
classifier.add(Dense(output_dim = 1, init = 'uniform', activation = 'sigmoid'))

# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, nb_epoch = 150)

/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:10: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", input_dim=7, units=4, kernel_initializer="uniform")`
  # Remove the CWD from sys.path while we load stuff.
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:13: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=4, kernel_initializer="uniform")`
  del sys.path[0]
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:16: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=4, kernel_initializer="uniform")`
  app.launch_new_instance()
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:19: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="sigmoid", units=1, kernel_initializer="uniform")`
/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:25: UserWarning: The `nb_epoch` argument in `fit` has been renamed 

Epoch 1/150
712/712 [==============================] - 1s 1ms/step - loss: 0.6907 - acc: 0.6166
Epoch 2/150
712/712 [==============================] - 0s 144us/step - loss: 0.6833 - acc: 0.6166
Epoch 3/150
712/712 [==============================] - 0s 133us/step - loss: 0.6621 - acc: 0.6166
Epoch 4/150
712/712 [==============================] - 0s 127us/step - loss: 0.6177 - acc: 0.6166
Epoch 5/150
712/712 [==============================] - 0s 127us/step - loss: 0.5808 - acc: 0.6166
Epoch 6/150
712/712 [==============================] - 0s 130us/step - loss: 0.5604 - acc: 0.6166
Epoch 7/150
712/712 [==============================] - 0s 127us/step - loss: 0.5461 - acc: 0.6166
Epoch 8/150
712/712 [==============================] - 0s 129us/step - loss: 0.5353 - acc: 0.6994
Epoch 9/150
712/712 [==============================] - 0s 124us/step - loss: 0.5300 - acc: 0.7978
Epoch 10/150
712/712 [==============================] - 0s 129us/step - loss: 0.5242 - acc: 0.8020
Epoch 11/150
712/712 

712/712 [==============================] - 0s 208us/step - loss: 0.4358 - acc: 0.8272
Epoch 84/150
712/712 [==============================] - 0s 164us/step - loss: 0.4354 - acc: 0.8287
Epoch 85/150
712/712 [==============================] - 0s 163us/step - loss: 0.4351 - acc: 0.8287
Epoch 86/150
712/712 [==============================] - 0s 147us/step - loss: 0.4349 - acc: 0.8287
Epoch 87/150
712/712 [==============================] - 0s 156us/step - loss: 0.4343 - acc: 0.8301
Epoch 88/150
712/712 [==============================] - 0s 135us/step - loss: 0.4346 - acc: 0.8287
Epoch 89/150
712/712 [==============================] - 0s 132us/step - loss: 0.4346 - acc: 0.8244
Epoch 90/150
712/712 [==============================] - 0s 145us/step - loss: 0.4335 - acc: 0.8315
Epoch 91/150
712/712 [==============================] - 0s 156us/step - loss: 0.4332 - acc: 0.8301
Epoch 92/150
712/712 [==============================] - 0s 180us/step - loss: 0.4329 - acc: 0.8315
Epoch 93/150
712/712 [=

In [250]:
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)

In [251]:
# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[99, 11],
       [23, 46]])

In [252]:
X_pred = df_test.iloc[:,0:7].values
X_pred
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_pred_1 = LabelEncoder()
X_pred[:, 6] = labelencoder_X_pred_1.fit_transform(X_pred[:, 6])

labelencoder_X_pred_2 = LabelEncoder()
X_pred[:, 1] = labelencoder_X_pred_2.fit_transform(X_pred[:, 1])

onehotencoder = OneHotEncoder(categorical_features = [1])
X_pred = onehotencoder.fit_transform(X_pred).toarray()
X_pred = X_pred[:, 1:]

In [253]:
y_pred = classifier.predict(X_pred)
y_pred
res = []
for y_list in y_pred:
    for y in y_list:
        tmp = 1 if(y_list > 0.5) else 0
        res.append(tmp)
res = pd.DataFrame(res, columns = ["Survived"])
results = pd.concat([PassengerId,res],axis=1)
results.to_csv('submission.csv', index=False)
results.head(5)

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0